<?php

namespace Yeepliva\Controllers;

/**
 * Yeepliva view.
 * 
 * The view generated by controllers.
 */
class View
{
  /**
   * Initialization.
   * 
   * @param string $content The view generated.
   * @return void
   */
  public function __construct(private string $content)
  {
  }

  /**
   * Display the generated view.
   * 
   * @return void
   */
  public function display(): void
  {
    echo $this->content;
  }
}